name: flutter_sweep
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  collection: ^1.19.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
